// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFmUaC0bV9o-thKT4dceDNtgM26NYtT88',
    appId: '1:733731329966:web:766c519bdeae888b16da3f',
    messagingSenderId: '733731329966',
    projectId: 'drivego-c822f',
    authDomain: 'drivego-c822f.firebaseapp.com',
    storageBucket: 'drivego-c822f.firebasestorage.app',
    measurementId: 'G-TRB4JQ2CXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBl-1kUpGEaKtwWiQofnOKRgc4UxMZyTM',
    appId: '1:733731329966:android:c8e689a9d1463bc416da3f',
    messagingSenderId: '733731329966',
    projectId: 'drivego-c822f',
    storageBucket: 'drivego-c822f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuukIa5SMMyPkcZMVLY4VjGNDVjH09Pkg',
    appId: '1:733731329966:ios:3306cedd958c240016da3f',
    messagingSenderId: '733731329966',
    projectId: 'drivego-c822f',
    storageBucket: 'drivego-c822f.firebasestorage.app',
    iosBundleId: 'com.example.driveGo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuukIa5SMMyPkcZMVLY4VjGNDVjH09Pkg',
    appId: '1:733731329966:ios:3306cedd958c240016da3f',
    messagingSenderId: '733731329966',
    projectId: 'drivego-c822f',
    storageBucket: 'drivego-c822f.firebasestorage.app',
    iosBundleId: 'com.example.driveGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFmUaC0bV9o-thKT4dceDNtgM26NYtT88',
    appId: '1:733731329966:web:a1de3befd0b9c3b816da3f',
    messagingSenderId: '733731329966',
    projectId: 'drivego-c822f',
    authDomain: 'drivego-c822f.firebaseapp.com',
    storageBucket: 'drivego-c822f.firebasestorage.app',
    measurementId: 'G-JJVTRHZCPV',
  );
}
